services:
  db:
    image: postgres:latest
    container_name: andb_lab1_postgres
    environment:
      POSTGRES_USER: user1234
      POSTGRES_PASSWORD: password5678
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
      - ./init_data:/init_data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: